### ISSUE TITLE
Landing PAGE

### ISSUE THREAD

**Issue by DeepeshKalura** [DeepeshKalura/event-planner-ai#1]
## Our application has the landing page:
1. Landing PAge must have a button which will send us to the main app.
2. The landing page must have number which will explain number of tourism vs event in a place
3. Explain the issue in the page, { what is the issue we see in the current tri valley }
4. Progress Solution what we our proposing
5. Numbers we are estimated can be improved in the tourism after our idea implemented.
6. Email Marketing tools connection like mailchip etc..

Hope you will design it good.
If you don't understand it, Just mention issue in the whatapp.

**Comment by soniyadotp** [comment]
Assign me

**Comment by DeepeshKalura** [comment]
@soniyaprasad77 ker dena pr raise

**Comment by DeepeshKalura** [comment]
Tu laptop dek ley 😂😂

**Comment by soniyadotp** [comment]
Past 12.00

**Comment by soniyadotp** [comment]
😌
